### ISSUE TITLE
cni network type is configured as calico but cni.go is looking for loopback binary

### ISSUE THREAD

**Issue by sbezverk** [tigera/canal#13]
Hello,
I do a fresh installation of canal cni plugin. Here is the file which get landed in /etc/cni/net.d

/etc/cni/net.d/10-canal.conf 
{
    "name": "canal",
    "type": "flannel",
    "delegate": {
      "type": "calico",
      "etcd_endpoints": "http://10.57.32.11:6666",
      "log_level": "debug",
      "policy": {
        "type": "k8s",
         "k8s_api_root": "https://10.57.32.1:443",
         "k8s_auth_token": "...removed ..."
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    }
}
so the type is clearly set to flannel and calico. Regardless of this conifg, cni.go generates error because it is looking for loopback binaries. Could you confirm if loopback binaries are required regardless of the plugin type selected. If it is the case then which process is responsible for copying these binaries.
If it is not the case then why cni ignores configured plugin type and keeps asking for loopback.

Oct 13 19:23:49 k8s-1 kubelet: E1013 19:23:49.618529    2297 pod_workers.go:184] Error syncing pod fce376f4-9192-11e6-8a7a-525400008e75, skipping: failed to "SetupNetwork" for "kube-dns-3306409432-uhgs6_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-3306409432-uhgs6_kube-system(fce376f4-9192-11e6-8a7a-525400008e75)\" using network plugins \"cni\": failed to find plugin \"loopback\" in path [/opt/loopback/bin /opt/cni/bin]; Skipping pod"

**Comment by caseydavenport** [comment]
@sbezverk I believe you're encountering this issue: https://github.com/kubernetes/kubernetes/issues/30681

As of Kubernetes v1.3.5, the `loopback` plugin is required no matter what CNI plugin you're using.  The guides in this repo assume that it is installed as one of the Kubernetes dependencies.

You can install the binary yourself from here: https://github.com/containernetworking/cni/releases

**Comment by caseydavenport** [comment]
@sbezverk I've raised https://github.com/tigera/canal/issues/14 to track this.  

It's unclear whether or not canal should be responsible for installing the loopback plugin, but maybe it makes sense to ease some of the pain for users.
