### ISSUE TITLE
Install loopback plugin

### ISSUE THREAD

**Issue by caseydavenport** [tigera/canal#14]
Kubernetes depends on the `loopback` plugin being installed. See here: https://github.com/kubernetes/kubernetes/issues/30681

Canal itself doesn't need this, but Kubernetes fails without it.  Should the self-hosted manifests support installing this binary?

In the meantime, users need to make sure they are installing a CNI release from here: https://github.com/containernetworking/cni/releases

**Comment by caseydavenport** [comment]
@tomdee What do you think? On one hand, it's not really a canal component. On the other hand, users hit this a lot.

**Comment by tomdee** [comment]
I'm not sure. The whole loopback plugin thing is a little "extreme". I think it's reasonably straightforward for us to add it, so maybe we should?

**Comment by caseydavenport** [comment]
Assigned to @heschlie since he's doing this for Calico CNI.

**Comment by heschlie** [comment]
Resolved in https://github.com/projectcalico/calico-cni/pull/211
