### ISSUE TITLE
Update the service cluserIP used for canal etcd in hosted install.

### ISSUE THREAD

**Issue by caseydavenport** [tigera/canal#16]
See here:  https://github.com/kubernetes/kubernetes.github.io/pull/1608/files#diff-d815373181beaa60de5c28956e4ba3fcR120

**Comment by caseydavenport** [comment]
@gunjan5 could you investigate this to make sure we work with the [latest kubeadm](http://kubernetes.io/docs/getting-started-guides/kubeadm/)?

**Comment by gunjan5** [comment]
Fixed in #21
