### ISSUE TITLE
Move to etcdless Canal

### ISSUE THREAD

**Issue by matthewdupre** [tigera/canal#19]
Currently you can install etcdless Flannel with [kube-flannel](https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml), and etcdless Calico (experimental) with https://raw.githubusercontent.com/projectcalico/calico/master/master/getting-started/kubernetes/installation/hosted/k8s-backend/calico.yaml.

Once the k8s backend for Calico has had a bit more testing; this repo should be updated to suggest this as the way.

**Comment by mattbates** [comment]
@seanturner83

**Comment by caseydavenport** [comment]
I've opened #25 to do this :)
